### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mioni** [ROFLailXGOD/twitch-farmer#15]
I've been using replit for a while and now it's giving me this error.

Traceback (most recent call last):
  File "/mi/runner/twitch/app.py", line 27, in <module>
    asyncio.run(run())
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/mi/runner/twitch/app.py", line 20, in run
    await asyncio.gather(
  File "/mi/runner/twitch/sources/new_api.py", line 104, in idle
    streamers = await get_active_streams(session)
  File "/mi/runner/twitch/sources/new_api.py", line 73, in get_active_streams
    if not streams['data']:
KeyError: 'data'

**Comment by ROFLailXGOD** [comment]
Did it work before and if so did you change anything?

**Comment by Mioni** [comment]
I didn't change anything, it was working for a few days and then when I came back to see it now it keeps giving me this error

**Comment by ROFLailXGOD** [comment]
Hmm, as far as I remember, the app would die after a few hours of running, but I never cared enough to find out why. As mentioned in the disclaimer, I made it for myself and this particular issue didn't bother me. Have you tried restarting? If yes, you could share your configuration and I'll try to look into it eventually. But I'll be honest, I stopped using this a long time ago, since Twitch stopped introducing these events that gave emotes. So it'll probably take me some time

**Comment by Mioni** [comment]
I got it by renewing the OAUTH tokens! Thanks!

**Comment by ROFLailXGOD** [comment]
Glad it works again!
